[project]
name = "pfl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kymatio>=0.3.0",
    "numpy>=1.26.4",
    "opacus>=1.5.3",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
]
